name: Run VCMP with Localtonet Tunnel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:  # Added 'steps' to define the steps in the job
    - name: Install required tools
      run: |
          wget http://v04.adtec.ovh/server/VCMP04_server_v39_linux64.zip
          unzip VCMP04_server_v39_linux64.zip
          rm VCMP04_server_v39_linux64.zip
          chmod 755 mpsvrrel64
          wget https://localtonet.com/download/localtonet-linux-x64.zip
          unzip localtonet-linux-x64.zip
          rm localtonet-linux-x64.zip
          chmod 755 localtonet 

    - name: Start VCMP
      env:
        PORT: 8192
      run: |
        ./mpsvrrel64 -port $PORT &

    - name: Delay before creating tunnel
      run: sleep 10

    - name: Start Localtonet Tunnel
      env:
        LOCALTONET_TOKEN: ${{ secrets.LOCALTONET_TOKEN }}
      run: |
        # Start the tunnel in the background
        ./localtonet authtoken $LOCALTONET_TOKEN &
        
        # Wait for the tunnel to establish
        sleep 5
        
        # Keep the job running indefinitely
        wait
