name: VCMP Server Setup

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  setup-localtonet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Localtonet
        run: |
          wget https://localtonet.com/download/localtonet-linux-x64.zip
          unzip localtonet-linux-x64.zip
          rm localtonet-linux-x64.zip

      - name: List current directory
        run: |
          ls -la  # List contents of the current directory to see what was extracted

      - name: Set permissions for Localtonet
        run: |
          chmod +x localtonet  # Adjust the path if necessary

      - name: Start Localtonet
        env:
          LOCALTONET_TOKEN: ${{ secrets.LOCALTONET_TOKEN }}
        run: |
          ./localtonet -token $LOCALTONET_TOKEN &  # Run in the background

  setup-vcmp-server:
    runs-on: ubuntu-latest
    needs: setup-localtonet  # This job depends on the previous job

    steps:
      - name: Download VCMP Server
        run: |
          wget http://v04.adtec.ovh/server/VCMP04_server_v39_linux64.zip
          unzip VCMP04_server_v39_linux64.zip
          rm VCMP04_server_v39_linux64.zip

      - name: Set permissions for VCMP Server
        run: |
          chmod +x mpsvrrel64  # Adjust the path if necessary

      - name: Start VCMP Server
        run: |
          ./mpsvrrel64
